spring:
  application:
    name: Gerencia de Estoque

#  profiles:
#    active: dev # Defino qual arquivo de application será utilizado

  servlet:
    multipart:
      max-file-size: 10MB # Tamanho máximo de arquivo individual
      max-request-size: 10MB # Tamanho máximo de requisição total

  jpa:
    open-in-view: true # Habilita a visualização das queries no console
    properties:
      hibernate:
        format_sql: true # Formata as queries no console



server:
  servlet:
    context-path: /api/v1 # Define o prefixo de todas URLs da api