spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerencia_estoque
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    enabled: true # Habilita o Flyway na aplicação
    locations: classpath:db/migration # Caminho dos scripts de migração