#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:3306/estoque
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create